---
- hosts: masters
  become: yes

  tasks:
    - name: copy misc files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
      with_list:
        - src: ../prometheus-kube/monitoring-chart
          dest: /tmp/monitoring-chart
        - src: ingress-controller-1.7.1-baremetal/deploy.yaml
          dest: /tmp/ingress-controller.yaml
        - src: ../../ingress.yaml
          dest: /tmp/nginx-ingress.yaml
        - src: ../../nginx-deployment.yaml
          dest: /tmp/nginx-deployment.yaml

    - name: install helm
      shell: |
            wget https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
            tar -zxvf helm-v3.12.0-linux-amd64.tar.gz
            mv linux-amd64/helm /usr/local/bin/helm
      args:
        chdir: $HOME
    
    - name: install demo nginx deployment
      shell: kubectl apply -f /tmp/nginx-deployment.yaml
      args:
        chdir: $HOME

    - name: install nginx ingress controller & ingress
      shell: |
            kubectl apply -f /tmp/ingress-controller.yaml
            sleep 30
            kubectl apply -f /tmp/nginx-ingress.yaml
      args:
        chdir: $HOME

    - name: install prometheus & grafana
      shell: |
            helm upgrade --install monitoring /tmp/monitoring-chart --set volumeIDs.prometheus="{{ prometheus_volume_id }}" --set volumeIDs.grafana="{{ grafana_volume_id }}"
      args:
        chdir: $HOME
