---
- hosts: "masters, workers"
  remote_user: ubuntu
  become: yes
  become_method: sudo
  become_user: root

  tasks:
    - name: Create containerd config file
      file:
        path: "/etc/modules-load.d/containerd.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/modules-load.d/containerd.conf"
        block: |
              overlay
              br_netfilter

    - name: modprobe
      shell: |
              modprobe overlay
              modprobe br_netfilter


    - name: Set system configurations for Kubernetes networking
      file:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        state: "touch"

    - name: Add conf for containerd
      blockinfile:
        path: "/etc/sysctl.d/99-kubernetes-cri.conf"
        block: |
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1
              net.bridge.bridge-nf-call-ip6tables = 1

    - name: Apply new settings
      command: sysctl --system

    # Added step for containerd to use the systemd cgroup
    - name: install containerd
      shell: |
            apt update && apt install -y containerd
            mkdir -p /etc/containerd
            containerd config default | tee /etc/containerd/config.toml
            sed -i 's/\(SystemdCgroup\s*=\s*\).*$/\1true/' /etc/containerd/config.toml
            systemctl restart containerd

    - name: disable swap
      shell: |
            swapoff -a
            sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: install and configure dependencies
      shell: |
            apt update && apt install -y ca-certificates curl
            curl -fsSLo /etc/apt/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
            echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list

    # - name: Create kubernetes repo file
    #   file:
    #     path: "/etc/apt/sources.list.d/kubernetes.list"
    #     state: "touch"

    # - name: Add K8s Source
    #   blockinfile:
    #     path: "/etc/apt/sources.list.d/kubernetes.list"
    #     block: |
    #           deb https://apt.kubernetes.io/ kubernetes-xenial main

    - name: install kubernetes
      shell: |
            apt update --allow-insecure-repositories
            apt install -y kubelet=1.26.4-00 kubeadm=1.26.4-00 kubectl=1.26.4-00 --allow-unauthenticated
            apt-mark hold kubelet kubeadm kubectl

    # A full system update must be done for Kubernetes 1.27 (maybe)
    # Switch to docker